name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - [opened, synchronize, reopen]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    name: "Java ${{ matrix.java }} build"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and Analyze
        run: |
         mvn -B -P metrics verify sonar:sonar \
            -Dsonar.organization=wren \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.projectKey=wren_test-commons \
            -Dsonar.java.pmd.reportPaths=target/pmd.xml \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.spotbugs.reportPaths=target/spotbugs.xml
